version: "3"

# All available services
# https://medium.com/@martinahindura/how-to-setup-metabase-with-postgresql-and-docker-compose-bf4cc7e7f899
services:
  metabase:
    container_name: "data-engine_metabase"
    restart: "always"
    image: metabase/metabase
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
    env_file:
      - ./config/metabase_database.env
    ports:
      - 3000:3000
 
  postgres:
    container_name: "data-engine_postgres"
    restart: "always"
    image: postgres
    env_file:
      - ./config/postgres.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432

# Volumes to persist data
volumes:
  postgres_volume:
